# Generated by Django 6.1.1 on 2026-09-12 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('in_transit', 'in_transit'), ('delivered', 'delivered')], default='created')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('incoming_status', models.CharField(choices=[('in_transit', 'in_transit'), ('delivered', 'delivered')])),
                ('state', models.CharField(choices=[('pending', 'pending'), ('done', 'done')])),
                ('attempts', models.IntegerField()),
                ('last_error', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('ignored', 'ignored'), ('applied', 'applied')])),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shipment')),
            ],
        ),
    ]
