# Generated by Django 6.1.1 on 2026-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_attempts_alter_event_last_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(choices=[('ignored', 'ignored'), ('applied', 'applied')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending'),
        ),
    ]
