# Generated by Django 6.1.1 on 2026-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_outcome_alter_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(blank=True, choices=[('ignored', 'ignored'), ('applied', 'applied')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
