# Generated by Django 6.1.1 on 2026-09-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_attempts_alter_event_last_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='shipment_id',
            new_name='shipment',
        ),
    ]
