# Generated by Django 6.1.1 on 2026-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_shipment_id_event_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
